### PR TITLE
update regex_dna to regex-0.1.41 and rustc 1.3.0

### PR DESCRIPTION
**Pull request by llogiq**
This hopefully solves #3, and gets rid of errors and deprecation warnings.

### CODE REVIEW

**Comment by BurntSushi** [comment]
LGTM. It also looks like the `regex-dna.rs` in this repo is out-of-sync with the copy on the game's web site (probably my fault): http://benchmarksgame.alioth.debian.org/u64/program.php?test=regexdna&lang=rust&id=2

**Comment by llogiq** [comment]
I'm unsure about the order of submitter lines though. Since @BurntSushi submitted the current version, he's got the last laugh, so to speak. I've left it as it is on alioth. However, next time we may change order yet again. Just thought I'd write it up now before it gets forgotten.

**Comment by TeXitoi** [comment]
Ok for the contributor order as other is already contributed.

For the regex installation, it could be great if it can be generalized as before. Like that, adding another dependency is very easy.

**Comment by TeXitoi** [comment]
And please add nightly to travis.

**Comment by TeXitoi** [comment]
Thanks for the good work :+1:

**Comment by llogiq** [comment]
My pleasure. My next commit will add nightly to travis and unify the dependency handling.

I have one remaining problem: The current version has removed the regex and typed-arena versions and uses `"*"` instead. If I want to re-introduce the versions, I need to somehow split the string into crate name and version number, but I haven't worked with Makefiles for a long time.

Edit: I think `$(firstword $(subst -,  , $*))` for the crate name and `$(lastword $(subst -,  , $*))` for the version might work; well, it doesn't for `typed-arena`, because of the hyphen in the name.

**Comment by llogiq** [comment]
Ok, I think I got it. @TeXitoi r?

**Comment by TeXitoi** [comment]
Thanks!

**Pull request merged**
