### PR TITLE
try container-based travis build

### PR DESCRIPTION
**Pull request by llogiq**
Seeing that the travis builds takes quite a while sometimes, why not try their new container-based infrastructure. I hear good things about it.

If this build passes, we also know that it works.

### CODE REVIEW

**Comment by llogiq** [comment]
So it doesn't work because we cannot install libgmp. I think there should be another way. I'll look into it.

**Comment by llogiq** [comment]
Now we can get the faster builds :smile:

**Comment by TeXitoi** [comment]
Thanks

**Comment by llogiq** [comment]
You're welcome.

**Pull request merged**
