### PR TITLE
Update to Rayon 0.7

### PR DESCRIPTION
**Pull request by mbrubeck**

### CODE REVIEW

**Comment by cristicbz** [comment]
Do you see any significant speed ups by any chance?

**Comment by mbrubeck** [comment]
I haven't run all the benchmarks to see. I verified that mandelbrot's speed was unchanged even after removing the deprecated `weight_max` call.  Reverse-complement appeared to have a small speedup, but the results were too noisy to tell for certain.

**Comment by TeXitoi** [comment]
Great! Should be proposed when 1.17 goes out.

**Review by TeXitoi — APPROVED** [review]

**Comment by mbrubeck** [comment]
https://alioth.debian.org/tracker/index.php?func=detail&aid=315724&group_id=100815&atid=413122

**Comment by TeXitoi** [comment]
oups, forgot. .

**Pull request merged**
