### PR TITLE
macroless n_body

### PR DESCRIPTION
**Pull request by llogiq**
As requested by Isaac. I now have my own account there so I can submit it.

### CODE REVIEW

**Review by TeXitoi — APPROVED** [review]

**Comment by TeXitoi** [comment]
Thanks.

**Comment by llogiq** [comment]
You're welcome. It'll be interesting to see how it performs on Isaacs machine.

**Comment by mbrubeck** [comment]
Unfortunately this performed worse than the old version on the benchmarksgame server. :(

× | source | secs | mem | gz | cpu | cpu load
-- | -- | -- | -- | -- | -- | --
1.6 | Rust #2 | 13.13 | 1,740 | 1805 | 13.12 | 1% 100% 0% 1%
2.6 | Rust #6 | 20.93 | 1,820 | 1790 | 20.93 | 100% 0% 1% 0%

**Comment by llogiq** [comment]
Yeah, I forgot that Isaac uses this ancient pre-AVX Core 2, which cannot do 256 bit float arithmetic :frown:.

On the other hand, I have an idea on how to improve perf even without that. Stay tuned.

**Pull request merged**
