### PR TITLE
regex_redux

### PR DESCRIPTION
**Pull request by mbrubeck**
regex-dna has been replaced by [regex-redux][1].  This PR replaces the regex-dna program and data files with converted regex-redux program and data files [from the web site][2].

*(edit: fixed links)*

[1]: https://alioth.debian.org/forum/forum.php?thread_id=14994&forum_id=2965&group_id=100815
[2]: http://benchmarksgame.alioth.debian.org/u64q/regexredux-description.html#regexredux

### CODE REVIEW

**Comment by BurntSushi** [comment]
FYI, this is my version that parallelizes replacements. With `aho-corasick >= 0.6.3` (just released), it's faster on my machine than the PHP version by about 5-10%. https://gist.github.com/anonymous/43a36658aec8d617a5367262fc909a29 --- I'll submit a PR with it if we think Isaac will take it, otherwise we can chuck it.

**Comment by mbrubeck** [comment]
> FYI, this is my version that parallelizes replacements.

As discussed on IRC, I believe this optimization is incorrect (and so are the PHP and Hack programs that use it).  I pointed this out [on the forum][1], so igouy can decide whether to disqualify those programs.

[1]: https://alioth.debian.org/forum/forum.php?thread_id=14994&forum_id=2965&group_id=100815

**Comment by mbrubeck** [comment]
I added some comments, and a small optimization that seems to reduce the running time by a few percent on my machine.  (It's hard to say for sure because the results are very noisy, but it's definitely an improvement on average.)

I plan to submit this to the game, but I'll wait a few days for the PHP question to be resolved and for any other improvements to be made.

**Comment by mbrubeck** [comment]
https://alioth.debian.org/tracker/index.php?func=detail&aid=315663&group_id=100815&atid=413122

**Comment by mbrubeck** [comment]
igouy has [tweaked][1] the new regexes slightly to prevent simple parallel replacement, invalidating the converted PHP and Hack programs that used that technique.  The Rust program and reference output have been converted to use the new substitution.

The Rust program is now close to the same speed as most of the programs that use PCRE (including PHP, Hack, and some of the C programs).  The fastest C programs also use double-buffering, allocating just two buffers and swapping them with each substitution, which is something that we can't easily do with the `regex` library (except maybe by writing our own substitution method that iterates over matches).

[1]: https://alioth.debian.org/forum/forum.php?thread_id=14993&forum_id=2965&group_id=100815

**Comment by BurntSushi** [comment]
The `aho-corasick 0.6.3` release appears significant. On my system, running this PR, I get `3.8s` with `aho-corasick 0.6.2`, `2.6s` with `aho-corasick 0.6.3` and with SIMD enabled I get `2s`. For comparison, the PCRE program takes `2.8s` on my machine. So if we can get Isaac to update aho-corasick, that might help improve things. :-) (The optimization was a single explicit loop unroll. Wowzahs.)

Command I used to run (to restrict to 4 CPUs):

```
$ time taskset 4 shootout-regex-redux < /data/texts/dna/regex-dna.fasta
```

And for the PCRE program, I used the same compile command on the benchmark game and ran it like this:

```
$ time taskset 4 ./regexredux < /data/texts/dna/regex-dna.fasta
```

**Comment by BurntSushi** [comment]
FWIW, I tried an approach where I was more judicious with buffers like the C program, and it doesn't seem to make much of a difference. Maybe jemalloc is handling it for us already? https://gist.github.com/anonymous/38c8fccaab5803df34a1d13b3551bd7f

**Comment by mbrubeck** [comment]
igouy says he’ll rebuild dependencies from scratch on the next compiler update, so we’ll just have to wait a few weeks for the Rust 1.17 release.

**Comment by TeXitoi** [comment]
Ok, the rules look stable now. Look like there is no better idea. Should I merge that?

**Comment by mbrubeck** [comment]
Yes, please. :+1:

**Comment by TeXitoi** [comment]
Thanks everyone !

**Comment by BurntSushi** [comment]
> igouy says he’ll rebuild dependencies from scratch on the next compiler update, so we’ll just have to wait a few weeks for the Rust 1.17 release.

Very reasonable! Thanks for asking. :-)

**Pull request merged**
