### PR TITLE
Mixed mutex/spinlock for thread_ring.

### PR DESCRIPTION
**Pull request by Veedrac**
I'm quite curious about how well this works on other people's computers (try both `time taskset 1 ./thread_ring` and `time taskset 15 ./thread_ring`).

I'm sending a PR here rather than to Rust because
1. Building Rust takes ages.
2. I'm still unsure about how well this actually works. I've gotten mixed results.

I've written an explanation about the strategy used below.

---

We have two primary conditions:
- Token passing must be _fast_.
- Almost all threads must be sleeping to avoid time wasted context-switching.

The first point suggests using atomics to exchange values, since they are much faster than mutexes. However, the second suggests mutexes, since having 502 busy-waiting threads is a recipe for disaster.

The solution taken here is to use both. A mutex is taken to keep threads asleep, but is unlocked one step early. An atomic spinlock is used on the live threads, allowing for fast data transfer. This pushes the mutex latency out of the fast path, although we're still bounded by mutex throughput.

When run with affinity to one core, this works quite nicely. However, since the working set is larger than the number of real threads, the thread-switching overhead isn't removed. This means it actually runs a bit slower (~20%) than using a single mutex as a lock.

When run with affinity to two cores, the strategy kicks in. Two threads are set up, one thread passes the token to the next and then replaces itself with the next thread in the chain by unlocking it and going to sleep (by waiting on a condition variable). This results in significant parallelism, and a really fast run.

When run with affinity to more than two cores, for some reason things start going weird. The exact results seem to vary from great to terrible depending on the precise number of cores and some other random variables, with little rhyme or reason. I'd appreciate attempted explanations or other people's timings on the four-core case.

One might think you could help the four-core case along by putting the mutex unlock further ahead, but that generates a lot of bus traffic that seems to slow things down.

### CODE REVIEW

**Comment by llogiq** [comment]
On my machine:

```
$ time bin/thread_ring 50000000
292

real    6m48.787s
user    2m52.222s
sys     4m46.770s
$ time bin/thread_ring_veedrac 50000000
292

real    3m45.992s
user    2m8.197s
sys     5m3.832s
```

About twice as fast as the previous version. Only a few orders of magnitude to catch up to Go or Haskell :smile:

Speaking of which, the trick the Go version pulls is that their goroutines are basically coroutines – one can see their implementation is basically single-threaded. The haskell version appears to use a different trick (based on STM) to get away without locking.

Oh, I see you wanted taskset results:

```
$ time taskset 1 bin/thread_ring_veedrac 50000000
292

real    3m41.677s
user    0m57.052s
sys     2m44.443s
$ time taskset 15 bin/thread_ring_veedrac 50000000
292

real    2m6.206s
user    1m23.460s
sys     2m44.623s
```

Faster still, but a long way to go.

**Comment by Veedrac** [comment]
Great; seems to be working. I'll run with it as-is... and if it gets pathological behaviour in the Benchmarks Game, such is life.

And, yeah, the aim was never to beat N-M threading - just the other implementations using real threads.

**Comment by TeXitoi** [comment]
I like this implementation, bit I also think that the simple (slow) implementation is also interesting. We need to find a way to have several versions of the same bench.

**Comment by Veedrac** [comment]
This has been submitted:

http://benchmarksgame.alioth.debian.org/u64q/performance.php?test=threadring
http://benchmarksgame.alioth.debian.org/u32/performance.php?test=threadring

This is the fastest program using real threads (in the multicore benchmark), as far as I can tell, although I'm a tad sad I didn't get more than a 10 second lead on C. Not being able to set thread affinities really hurts.

**Comment by TeXitoi** [comment]
As this version is submitted to the benchmarksgame, I close the PR.

**Pull request closed without merging**
